
cur_mkfile := $(abspath $(lastword $(MAKEFILE_LIST)))
ROOT :=$(patsubst %/, %, $(dir $(cur_mkfile)))

all:VuxTest.exe
VuxTest.exe: $(ROOT)/VuxObjs/CString_1.o $(ROOT)/VuxObjs/_4T_DataBasic_1.o $(ROOT)/VuxObjs/_7U_EditCaseCode_1.o $(ROOT)/VuxObjs/_6T_WhiteBox_1.o $(ROOT)/VuxObjs/_2Y_SendMail_1.o $(ROOT)/VuxObjs/_3U_MyClass_1.o $(ROOT)/VuxObjs/_4U_DataBasic_1.o $(ROOT)/VuxObjs/student_1.o $(ROOT)/VuxObjs/_2T_SendMail_1.o $(ROOT)/VuxObjs/_1T_Begin_1.o $(ROOT)/VuxObjs/_1Y_Begin_1.o $(ROOT)/VuxObjs/_5U_InsideIO_1.o $(ROOT)/VuxObjs/test_1.o $(ROOT)/VuxObjs/autocase_1.o $(ROOT)/VuxObjs/_2U_SendMail_1.o $(ROOT)/VuxObjs/CMapStringToPtr_1.o $(ROOT)/VuxObjs/_3Y_MyClass_1.o $(ROOT)/VuxObjs/_1U_Begin_1.o $(ROOT)/VuxObjs/_7T_EditCaseCode_1.o $(ROOT)/VuxObjs/_8Y_String_1.o $(ROOT)/VuxObjs/_3T_MyClass_1.o $(ROOT)/VuxObjs/_6U_WhiteBox_1.o $(ROOT)/VuxObjs/_5T_InsideIO_1.o $(ROOT)/VuxObjs/VuxMain_2.o
	g++  -o $(ROOT)/VuxTest.exe $(ROOT)/VuxObjs/CString_1.o $(ROOT)/VuxObjs/_4T_DataBasic_1.o $(ROOT)/VuxObjs/_7U_EditCaseCode_1.o $(ROOT)/VuxObjs/_6T_WhiteBox_1.o $(ROOT)/VuxObjs/_2Y_SendMail_1.o $(ROOT)/VuxObjs/_3U_MyClass_1.o $(ROOT)/VuxObjs/_4U_DataBasic_1.o $(ROOT)/VuxObjs/student_1.o $(ROOT)/VuxObjs/_2T_SendMail_1.o $(ROOT)/VuxObjs/_1T_Begin_1.o $(ROOT)/VuxObjs/_1Y_Begin_1.o $(ROOT)/VuxObjs/_5U_InsideIO_1.o $(ROOT)/VuxObjs/test_1.o $(ROOT)/VuxObjs/autocase_1.o $(ROOT)/VuxObjs/_2U_SendMail_1.o $(ROOT)/VuxObjs/CMapStringToPtr_1.o $(ROOT)/VuxObjs/_3Y_MyClass_1.o $(ROOT)/VuxObjs/_1U_Begin_1.o $(ROOT)/VuxObjs/_7T_EditCaseCode_1.o $(ROOT)/VuxObjs/_8Y_String_1.o $(ROOT)/VuxObjs/_3T_MyClass_1.o $(ROOT)/VuxObjs/_6U_WhiteBox_1.o $(ROOT)/VuxObjs/_5T_InsideIO_1.o $(ROOT)/VuxObjs/VuxMain_2.o -L$(ROOT)/VuxLib -lvuxwin
$(ROOT)/VuxObjs/CString_1.o : $(ROOT)/Code/Demo/CString.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/CString.cpp -o $(ROOT)/VuxObjs/CString_1.o
$(ROOT)/VuxObjs/_4T_DataBasic_1.o : $(ROOT)/Code/Demo/_4T_DataBasic.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_4T_DataBasic.cpp -o $(ROOT)/VuxObjs/_4T_DataBasic_1.o
$(ROOT)/VuxObjs/_7U_EditCaseCode_1.o : $(ROOT)/Code/Demo/_7U_EditCaseCode.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_7U_EditCaseCode.cpp -o $(ROOT)/VuxObjs/_7U_EditCaseCode_1.o
$(ROOT)/VuxObjs/_6T_WhiteBox_1.o : $(ROOT)/Code/Demo/_6T_WhiteBox.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_6T_WhiteBox.cpp -o $(ROOT)/VuxObjs/_6T_WhiteBox_1.o
$(ROOT)/VuxObjs/VuxMain_2.o : $(ROOT)/Code/VuxMain.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/VuxMain.cpp -o $(ROOT)/VuxObjs/VuxMain_2.o
$(ROOT)/VuxObjs/_2Y_SendMail_1.o : $(ROOT)/Code/Demo/_2Y_SendMail.c
	gcc -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_2Y_SendMail.c -o $(ROOT)/VuxObjs/_2Y_SendMail_1.o
$(ROOT)/VuxObjs/_3U_MyClass_1.o : $(ROOT)/Code/Demo/_3U_MyClass.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_3U_MyClass.cpp -o $(ROOT)/VuxObjs/_3U_MyClass_1.o
$(ROOT)/VuxObjs/_4U_DataBasic_1.o : $(ROOT)/Code/Demo/_4U_DataBasic.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_4U_DataBasic.cpp -o $(ROOT)/VuxObjs/_4U_DataBasic_1.o
$(ROOT)/VuxObjs/student_1.o : $(ROOT)/Code/Demo/student.c
	gcc -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/student.c -o $(ROOT)/VuxObjs/student_1.o
$(ROOT)/VuxObjs/_2T_SendMail_1.o : $(ROOT)/Code/Demo/_2T_SendMail.c
	gcc -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_2T_SendMail.c -o $(ROOT)/VuxObjs/_2T_SendMail_1.o
$(ROOT)/VuxObjs/_1T_Begin_1.o : $(ROOT)/Code/Demo/_1T_Begin.c
	gcc -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_1T_Begin.c -o $(ROOT)/VuxObjs/_1T_Begin_1.o
$(ROOT)/VuxObjs/_1Y_Begin_1.o : $(ROOT)/Code/Demo/_1Y_Begin.c
	gcc -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_1Y_Begin.c -o $(ROOT)/VuxObjs/_1Y_Begin_1.o
$(ROOT)/VuxObjs/_5U_InsideIO_1.o : $(ROOT)/Code/Demo/_5U_InsideIO.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_5U_InsideIO.cpp -o $(ROOT)/VuxObjs/_5U_InsideIO_1.o
$(ROOT)/VuxObjs/test_1.o : $(ROOT)/Code/Demo/test.c
	gcc -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/test.c -o $(ROOT)/VuxObjs/test_1.o
$(ROOT)/VuxObjs/autocase_1.o : $(ROOT)/Code/Demo/autocase.c
	gcc -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/autocase.c -o $(ROOT)/VuxObjs/autocase_1.o
$(ROOT)/VuxObjs/_2U_SendMail_1.o : $(ROOT)/Code/Demo/_2U_SendMail.c
	gcc -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_2U_SendMail.c -o $(ROOT)/VuxObjs/_2U_SendMail_1.o
$(ROOT)/VuxObjs/CMapStringToPtr_1.o : $(ROOT)/Code/Demo/CMapStringToPtr.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/CMapStringToPtr.cpp -o $(ROOT)/VuxObjs/CMapStringToPtr_1.o
$(ROOT)/VuxObjs/_3Y_MyClass_1.o : $(ROOT)/Code/Demo/_3Y_MyClass.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_3Y_MyClass.cpp -o $(ROOT)/VuxObjs/_3Y_MyClass_1.o
$(ROOT)/VuxObjs/_1U_Begin_1.o : $(ROOT)/Code/Demo/_1U_Begin.c
	gcc -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_1U_Begin.c -o $(ROOT)/VuxObjs/_1U_Begin_1.o
$(ROOT)/VuxObjs/_7T_EditCaseCode_1.o : $(ROOT)/Code/Demo/_7T_EditCaseCode.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_7T_EditCaseCode.cpp -o $(ROOT)/VuxObjs/_7T_EditCaseCode_1.o
$(ROOT)/VuxObjs/_8Y_String_1.o : $(ROOT)/Code/Demo/_8Y_String.c
	gcc -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_8Y_String.c -o $(ROOT)/VuxObjs/_8Y_String_1.o
$(ROOT)/VuxObjs/_3T_MyClass_1.o : $(ROOT)/Code/Demo/_3T_MyClass.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_3T_MyClass.cpp -o $(ROOT)/VuxObjs/_3T_MyClass_1.o
$(ROOT)/VuxObjs/_6U_WhiteBox_1.o : $(ROOT)/Code/Demo/_6U_WhiteBox.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_6U_WhiteBox.cpp -o $(ROOT)/VuxObjs/_6U_WhiteBox_1.o
$(ROOT)/VuxObjs/_5T_InsideIO_1.o : $(ROOT)/Code/Demo/_5T_InsideIO.cpp
	g++ -c  -fpack-struct=8 -w -I$(ROOT)/ -I$(ROOT)/Code -I$(ROOT)/Code/Demo/ -IC:/Visual_Unit_4/_Compiler/gcc_4/include -IC:/Visual_Unit_4/_Compiler/gcc_4/lib/gcc/mingw32/4.9.2/include -D_WIN32 -DWIN32 -DWINDOWS -D_WINDOWS -D_DEBUG -DDEBUG $(ROOT)/Code/Demo/_5T_InsideIO.cpp -o $(ROOT)/VuxObjs/_5T_InsideIO_1.o
clean:
	cd $(ROOT)/VuxObjs && del *.o
	cd $(ROOT) && del VuxTest.exe